import type { NextPage } from 'next'
import Head from 'next/head'
import dynamic from 'next/dynamic'

import { Event, News } from '../types'
import EventCarousel from '../components/EventCarousel'
import Layout from '../containers/Layout'
import NewsCard from '../components/NewsCard'

import fixture from '../fixtures/home'
import projects from '../fixtures/projects'
import styles from '../styles/pages/Home.module.scss'

interface HomeProps {
  news: News[]
  events: Event[]
}

const DynamicPixelHero = dynamic(() => import('../components/PixelHero'))

const Home: NextPage<HomeProps> = ({ news, events }) => {
  const items = projects[0].artworks?.slice(0, 100) || []
  return (
    <Layout greyBG>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={styles.heroWrapper}>
        <DynamicPixelHero items={items} />
      </section>
      <section className={styles.newsAndEventsWrapper}>
        <div className={styles.eventsWrapper}>
          <p>EVENTS</p>
          <div className={styles.carouselWrapper}>
            <EventCarousel events={events} />
          </div>
        </div>
        <div className={styles.newsWrapper}>
          <p>NEWS</p>
          <div className={styles.newsCardWrapper}>
            {news?.map((item, i) => (
              <NewsCard
                key={`${item.title}${i}`}
                img={item.img}
                alt={item.alt}
                title={item.title}
              />
            ))}
          </div>
        </div>
      </section>
      <section style={{ height: '100vh', backgroundColor: 'white' }}></section>
      <section style={{ height: '100vh', backgroundColor: 'black' }}></section>
    </Layout>
  )
}

export async function getStaticProps() {
  return {
    props: fixture,
    revalidate: 60 * 60 * 24 // TODO: currently set to 1 day. Update if required
  }
}

export default Home
